config/routes.rb
PMC4::Application.routes.draw do

  resources :notices
  get 'config/show' => 'config#show', as: 'show_config'

  get 'scanners/scan' => 'scanners#scan', as: 'scan_scanners'
  get 'scanners/match' => 'scanners#match', as: 'match_scanners'
  post 'scanners/match' => 'scanners#match', as: 'match_scanners_post'

  get 'scanners/msas' => 'scanners#msas', as: 'msas_scanners'
  get 'scanners/msytdl' => 'scanners#msytdl', as: 'msytdl_scanners' # youtube dl


  resources :scanners do
    get 'copy', :on => :member
    get 'scann', :on => :member
    get 'extract', :on => :member
    get 'extractsave', :on => :member
  end

  resources :bookmarks do
    get 'getTitle', :on => :member
    get 'scan', :on => :member
    post 'search', :on => :collection
    get 'linkFolder', :on => :member
  end

  resources :mtypes


  resources :matches do
    get 'match', :on => :collection
    get 'extract', :on => :member
    get 'extractsave', :on => :member

  end

  resources :regurls do

    get 'check', :on => :member
    get 'match', :on => :collection

  end


  resources :agroups
  patch 'agroups' => 'agroups#indexedit', as: 'indexedit_agroups'

  get 'attris/find' => 'attris#find', as: 'find_attris'
  get 'attris/indi' => 'attris#indi', as: 'indi_attris'
  get 'attris/:id/find' => 'attris#find', as: 'find_attris2'

  get 'uris/show'  => "uris#show", as: 'uris_show'
  get 'uris/matchURL'  => "uris#matchURL", as: 'matchURL_uris'
  get 'uris/matchDir'  => "uris#matchDir", as: 'uris_matchDir'

  get 'uris/fetch'  => "uris#fetch", as: 'fetch_uris'
  get 'uris/save'  => "uris#save", as: 'save_uris'

  get 'uris/getLinks'  => "uris#getLinks", as: 'getLinks_uris'

  resources :attris do
    get 'autocomplete', :on => :collection
    get 'overview', :on => :collection
  end

  resources :mfiles do
    post 'add_attri_name', :on => :member
    post 'add_attri', :on => :member
    delete 'remove_attri', :on => :member
    post 'add_agroup', :on => :member
    delete 'remove_agroup', :on => :member
    get 'edit0', :on => :member
    get 'new_tag', :on => :member
    get 'update_tag', :on => :member
    get 'delete_tag', :on => :member
    get 'pic', :on => :member
    get 'path', :on => :member
    get 'youtubeLink', :on => :member
    get 'renderMfile', :on => :member
    get  'classify', :on => :collection
    get  'slideshow', :on => :collection
    post 'set_attris', :on => :collection
    get  'thumbs', :on => :collection
    get 'download', :on => :member
  end

  resources :folders do
    post 'copyFiles', :on => :member
    post 'generateTNs', :on => :member
    get 'changeStorage', :on => :member
    post 'checkForVideoFiles', :on => :member

  end




  patch 'folders' => 'folders#indexedit', as: 'indexedit_folders'

  resources :locations do
    get 'analyzeFiles', :on => :member
    get 'deleteFiles', :on => :member
    get 'copyToFiles', :on => :member
    get 'downloadToFiles', :on => :member
    get 'parse', :on => :member
    get 'getTitle', :on => :member
    post 'gswl', :on => :member
    get 'checkAvail', :on => :member
    get 'parseURL', :on => :member
    get 'scan', :on => :member
    get 'ls', :on => :member
  end

  resources :storages do
    get 'detectfolders', :on => :member
    get 'detectfiles', :on => :member
    get 'detectFaFs', :on => :member
    get 'make_thumbnails', :on => :member
    post 'touchMfiles', :on => :member
    post 'generateTNs', :on => :member
  end










end

app/models/scanner.rb
class Scanner < ApplicationRecord

  attr_accessor :urlExtern
  attr_accessor :lastMatch 

  @@cache = true

  def matches?(url)

    regex = %r{#{match}}
    result = regex.match(url)
    @lastMatch = result
    result 

  end

  def matchS(url)
     if matches?(url)
     	" FIT "
     else 
     	" --- "
     end
  end

  def scan(url)

#def self.extract(url, tag, attr, pattern)
    
    sourcee = Scanner.loadURL(url)
    if sourcee == "URL Load Error"
        links = ["Error"]
    end

    if tag.strip == ""
      links = []
      links[0] = sourcee
    else 
    page = Nokogiri::HTML(sourcee)

    urlbase = url
    
    links = page.css(tag)
  
    i = 0
    links = links.map { |l| 
      begin
      if attr and attr.length >0 
        URI.decode(URI.join(urlbase, URI.encode((l.attr(attr)||"").to_s)).to_s)
      else 
        i = i  + 1
        l.text.to_s
      end
      rescue
     jllj
        "failure"
      end
      } 
    
    end

    pa = pattern
    pattern = pa.sub("<url>",url)

    links.select! { |l| l[%r{#{pattern}}] } if pattern
    if pattern and pattern.length >0 
        links.map! { |link| 
          %r{#{pattern}}.match(link)[1]
        } 
    end

  links
 
  end

  def self.matchAndScan(url, level = 0, maxdepth=3, scanners=nil, result={})

    maxdepth = maxdepth - 1
    return {} if maxdepth < 0
    scanners ||= Scanner.all
    scanners.each {|s|
       if s.matches?(url)
          if s.stype  and s.stype != ""
            result[url] = [level,s.stype]
          end
            thislinks = s.scan(url).uniq # uniq added 20171014
            thislinks.each {|l|
               unless result[l]          # if link is not already found 
                  result[l] = [level, s.final]
                  unless s.final == "x" or s.final == "Error"
                     u =  Scanner.matchAndScan(l, level + 1, maxdepth, scanners, result)
                  end
      	       end
       	    }
#          else
#		jlj
#	  end 
       end
    } 
    result 
 end

  def self.matchAndScanBak(url, level = 0, maxdepth=3, scanners=nil)
    maxdepth = maxdepth - 1
    return [] if maxdepth < 0

    scanners ||= Scanner.all
    links = []
    scanners.each {|s|

        if s.matches?(url) 
          
          thislinks = s.scan(url).uniq # uniq added 20171014
          thislinks.map! {|l| [l, level, s.final]}
          unless s.final == "x" or s.final == "Error"
            nextlinks = []
            thislinks.each {|l|
              nextlinks << l
              nextlinks += matchAndScan(l[0], level + 1, maxdepth, scanners)
            } 
            thislinks = nextlinks if nextlinks.length > 0 
          end
          links += thislinks
        end
    } 
    links
  end


def self.createFolder(foldername, folderTitle,location)
    

    f = Folder.where(storage_id: location.storage.id, mpath: foldername, lfolder: "")
    if !f.empty?
       folder= f.first
    else
      folder = Folder.new
      folder.mpath = foldername
      folder.lfolder = ""
      folder.title = folderTitle
      folder.storage_id = location.storage_id
      folder.save
    end 
    location.mkDirectories(folder)
    return folder

end

def self.createFolderAndMfiles(url,links,location)

    linksToSave =  links.select{|url,l| l[1]=="x"    }.map{|url,l| url.rstrip}
    folderTitles = links.select{|url,l| l[1]=="title"}.map{|url,l| url.rstrip}
    if folderTitles.length > 0
      folderTitle = folderTitles[0]
    else 
      folderTitle = ""
    end  

    @commonStart = Scanner.detCommonStart(links)
    locationLength = location.uri.length
    ldiff = - @commonStart.length + locationLength 
    if ldiff < 0 
       foldername = @commonStart[ldiff..-1]   
    else
       foldername = ""
    end 
    folder = Folder.new
    
    folder.mpath = foldername
    folder.lfolder = ""
    folder.title = folderTitle

    folder.storage_id = location.storage_id
    folder.save

    offsetLength = foldername.length + locationLength

    linksToSave.each {|l|

      mfile = Mfile.new
      mfile.folder_id = folder.id
      ldiff = offsetLength - l.length
      mfile.filename = l[ldiff..-1]
      mfile.mtype = MFILE_IMEDIUM # 20171015
      mfile.save
    }

   folder
end


def self.createFolderAndMfilesBak(url,links,location)

    linksToSave =  links.select{|l| l[2]=="x"}.map{|l| l[0].rstrip}.uniq
    folderTitles =  links.select{|l| l[2]=="title"}.map{|l| l[0].rstrip}.uniq
    if folderTitles.length > 0
      folderTitle = folderTitles[0]
    else 
      folderTitle = ""
    end  

    @commonStart = Scanner.detCommonStart(links)
    locationLength = location.uri.length
    ldiff = - @commonStart.length + locationLength 
    if ldiff < 0 
       foldername = @commonStart[ldiff..-1]   
    else
       foldername = ""
    end 

    folder = Folder.new
    
    folder.mpath = foldername
    folder.lfolder = ""
    folder.title = folderTitle

    folder.storage_id = location.storage_id
    folder.save

    offsetLength = foldername.length + locationLength

    linksToSave.each {|l|

      mfile = Mfile.new
      mfile.folder_id = folder.id
      ldiff = offsetLength - l.length
      mfile.filename = l[ldiff..-1]
      mfile.mtype = 2 ########### muss noch im Dialog abgefragt werden
      mfile.save
    }
#   new Folder

#  mfile.folder

   folder
end



def self.detCommonStartNew(st)

  st.sts.each {|s|
  }

end

def self.detCommonStart(links)

   cs = nil
   x = 0
   links.each {|link, value| 
      next unless value[1] == "x" # take only finals
      l = link.strip          # the url
      x = x + 1
      if !cs
        cs = l
      else
        len = l.length
        len = cs.length if len>cs.length
        j = -1
        (0...len).each { |i|
          break if cs[i] != l[i]
          j = j + 1
        }
        cs = l[0..j]
      end
   }

   return "" unless cs
  /(.*\/)/.match(cs)[1].strip
end

def self.detCommonStartBak(links)

   cs = nil
   x = 0
   links.each {|link| 
      next unless link[2] == "x" # take only finals
      l = link[0].strip          # the url
      x = x +1
 #     break if x >211
      if !cs
        cs = l
      else
        len = l.length
        len = cs.length if len>cs.length
        j = -1
        (0...len).each { |i|
          break if cs[i] != l[i]
          j = j + 1
        }
        cs = l[0..j]
      end
   }

   return "" unless cs
  /(.*\/)/.match(cs)[1].strip
end


def self.loadURL(u)
 
 if u == "clear"
    @@cache = false
 end
 if u == "cache"
    @@cache = true
 end

# if true
#    Rails.cache.delete(u)
# end

    Rails.cache.fetch(u, expires_in: 12.hours) do
        begin
         open(u).read  #1
 
#1          uri = URI.parse(u)
          
#	  pams = { :id => 97563, :page => 3 }
#          uri.query = URI.encode_www_form(pams)

#1          req = Net::HTTP::Get.new(uri.request_uri)
#1          req['Referer'] = uri.scheme+"://"+uri.host
#1          Net::HTTP.start(uri.host, uri.port) do |http|
#1              response = http.request(req)
#1              response.body 
#1         end

#       rescue 
#          "URL Load Error"
        end
    end
 end


end

app/controllers/scanners_controller.rb
class ScannersController < ApplicationController
  before_action :set_scanner, only: [:show, :edit, :update, :destroy, :scann]

  # GET /scanners
  # GET /scanners.json
  def index
    @scanners = Scanner.all
    @scanners = @scanners.sort {|a,b| a.url <=> b.url}
  end

  def match

    @url = params[:url]
    @bookmark_id = params[:bookmark_id]
    unless @bookmark_id
      bo = Bookmark.find_by_url(@url)
      if bo
        @bookmark_id = bo.id
      end
    end

    @urly = Urly.new(@url)
    location_id = params[:location_id]
    @location = Location.find(location_id) if location_id
    if  params[:commit] == "Match and Scan"
      matchAndScan
    end
    @scanners = Scanner.all
    @scanners = @scanners.sort {|a,b| b.matchS(@url).to_s+a.url <=> a.matchS(@url).to_s+b.url}

  end

  def matchAndScan
    @url = params[:url]
    @bookmark_id = params[:bookmark_id]

    @links = Scanner.matchAndScan(@url)
    if @links.select{|a,b| b[1]=="YT"}.empty?

      @commonStart = Scanner.detCommonStart(@links)
      @possibleLocations = Location.all.select{|l| @commonStart.include? l.uri} # besser auf der DB ???
      render :scanResult
    else
      @possibleLocations = Location.all.where(typ: 2)
      render :scanResultYT
    end

  end

  def msytdl # match scan youtube download
    @url = params[:url]
    @links = Scanner.matchAndScan(@url)
     location_id = params[:location_id]
     location = Location.find(location_id)

    user, x = @links.select{|a,b| b[1]=="user"}.first
    #title, x = @links.select{|a,b| b[1]=="title"}.first
    user = user.lstrip
    title = user 
    folder = Scanner.createFolder("/"+user+"/", title,location)
    location.downloadTube(folder, @url)

     @bookmark_id = params[:bookmark_id]
       if @bookmark_id
         bm = Bookmark.find(@bookmark_id)
         bm.folder_id = folder.id
         bm.title = folder.title
         bm.save
       else
         bm = Bookmark.new(url: @url, folder_id: folder.id, title: folder.title)
         bm.save
        end

    redirect_to folder
  end

  def msas # match scan and save
     @url = params[:url]
     @bookmark_id = params[:bookmark_id]
     location_id = params[:location_id]
     if location_id and @url
       @location = Location.find(location_id)
       @links = Scanner.matchAndScan(@url)
       folder = Scanner.createFolderAndMfiles(@url,@links,@location)
       if @bookmark_id
         bm = Bookmark.find(@bookmark_id)
         bm.folder_id = folder.id
         bm.title = folder.title
         bm.save
       else
         bm = Bookmark.new(url: @url, folder_id: folder.id, title: folder.title)
         bm.save
        end
       redirect_to folder_path(folder)
     else

     end
  end

  # GET /scanners/1
  # GET /scanners/1.json
  def show
  end

  # GET /scanners/new
  def new
       @scanner = Scanner.new
  end

  # GET /scanners/new
  def copy
     if params[:id]
       @scanner = Scanner.find(params[:id]).dup
       @scanner.url = params[:urlExtern] if params[:urlExtern]
     else
       @scanner = Scanner.new
    end
     render :new
  end

  # GET /scanners/1/edit
  def edit
  end

  def scann
    @url = params[:url]
#      @links = RHandler.extract(@url,@scanner.tag,@scanner.attr,@scanner.pattern)
   #  @links = RHandler.scanAndMatch(@url,2)
      @links = @scanner.scan(@url)
  end

  def scan
    if params[:scanner]
       @scanner = Scanner.new(scanner_params)

       if  params[:commit] == "Scan"
         @links = RHandler.extract(@scanner.url,"a",@scanner.pattern)
       else
         @scanner.save
          redirect_to @scanner, notice: 'Scanner was successfully created.'
       end
    else
       @scanner = Scanner.new
    end
  end


  # POST /scanners
  # POST /scanners.json
  def create
    @scanner = Scanner.new(scanner_params)

    respond_to do |format|
      if @scanner.save

        format.html { redirect_to @scanner, notice: 'Scanner was successfully created.' }
        format.json { render :show, status: :created, location: @scanner }
      else
        format.html { render :new }
        format.json { render json: @scanner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scanners/1
  # PATCH/PUT /scanners/1.json
  def update
    respond_to do |format|
      if @scanner.update(scanner_params)
        if  params[:commit] == "Scan"
           @links = RHandler.extract(@scanner.url,@scanner.tag,@scanner.attr, @scanner.pattern)
        end
        format.html { render :edit, notice: 'Scanner was successfully updated.' }
        format.json { render :show, status: :ok, location: @scanner }
      else
        format.html { render :edit }
        format.json { render json: @scanner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scanners/1
  # DELETE /scanners/1.json
  def destroy
    @scanner.destroy
    respond_to do |format|
      format.html { redirect_to scanners_url, notice: 'Scanner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scanner
      @scanner = Scanner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scanner_params
      params.require(:scanner).permit(:tag, :attr, :pattern, :scan, :url, :location, :name, :match, :final, :stype)
    end
end

app/helpers/scanners_helper.rb
module ScannersHelper
end

app/views/scanners/_form.html.erb
<%= form_for(scanner) do |f| %>
  <% if scanner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scanner.errors.count, "error") %> prohibited this scanner from being saved:</h2>

      <ul>
      <% scanner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url, size: 80 %>
  </div>

  <div class="field">
    <%= f.label :stype %>
    <%= f.text_field :stype, size: 20 %>
  </div>


  <div class="field">
    <%=  @scanner.matchS(@scanner.url) %>

  </div>

  <div class="field">
    <%= f.label :match %>
    <%= f.text_field :match, size: 80 %>
  </div>

  <div class="field">
    <%= f.label :tag %>
    <%= f.text_field :tag %>
  </div>

  <div class="field">
    <%= f.label :attr %>
    <%= f.text_field :attr %>
  </div>

  <div class="field">
    <%= f.label :pattern %>
    <%= f.text_field :pattern %>
  </div>

  <div class="field">
    <%= f.label :final %>
    <%= f.text_field :final %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  <div class="actions">
    <%= submit_tag "Scan" %>
  </div>

<% end %>

app/views/scanners/_formScan.html.erb
<%= form_for scanner, url: {action: "scan"} do |f| %>
  <% if scanner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scanner.errors.count, "error") %> prohibited this scanner from being saved:</h2>

      <ul>
      <% scanner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url, size: 80 %>
  </div>


  <div class="field">
    <%= f.label :match %>
    <%= f.text_field :match %>
  </div>

  <div class="field">
    <%= f.label :tag %>
    <%= f.text_field :tag %>
  </div>

  <div class="field">
    <%= f.label :pattern %>
    <%= f.text_field :pattern %>
  </div>

  <div class="actions">
    <%= submit_tag "Scan" %>
  </div>
  <div class="actions">
    <%= submit_tag "Create" %>
  </div>
<% end %>

app/views/scanners/edit.html.erb
<h1>Editing Scanner</h1>

<%= render 'form', scanner: @scanner %>

<ul>
<% if @links %>
<% @links.each do |link| %>
<li>  <%=link_to link, link%>
	  <%=link_to "Match", match_scanners_path(url: link) %>
	
</li>
<% end %>
<% end %>
</ul>


<%= link_to 'Show', @scanner %> |
<%= link_to 'Back', scanners_path %>

app/views/scanners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scanners</h1>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Example URL</th>
      <th>match</th>
      <th>Tag</th>
      <th>Pattern</th>
      <th>Final</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scanners.each do |scanner| %>
      <tr>
        <td><%= scanner.name %></td>
        <td><%= scanner.url %></td>
        <td><%= scanner.match %></td>
        <td><%= scanner.tag %></td>
        <td><%= scanner.pattern %></td>
        <td><%= scanner.final %></td>
        <td><%= link_to 'Show', scanner %></td>
        <td><%= link_to 'Edit', edit_scanner_path(scanner) %></td>
        <td><%= link_to 'Destroy', scanner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scanner', new_scanner_path %>

app/views/scanners/match.html.erb
<p id="notice"><%= notice %></p>

<h1>Scanners</h1>


 <%= form_tag(match_scanners_path) do %>
  <div class="field">
    <%= label_tag :url %>
    <%= text_field_tag :url, @url, size: 80 %>
    <% if @bookmark_id %>
     <%= @bookmark_id %>
    <%= hidden_field_tag :bookmark_id, @bookmark_id %>
    <% end %>
  <%= submit_tag("Match") %>
  <%= submit_tag("Match and Scan") %>
  </div>
  <% if @location %>
  <div class="field">
    <%= label_tag :location %>
    <%= @location.name %> <%= @location.uri %>
    <%= hidden_field_tag "location_id", @location.id %>
  <%= submit_tag("Match and Scan") %>
  </div>
  <%end %>
<% end %>



<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Example URL</th>
      <th>Match</th>
      <th>Tag</th>
      <th>Pattern</th>
      <th>Fit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scanners.each do |scanner| %>
      <tr>
        <td><%= scanner.name %></td>
        <td><%= scanner.url %></td>
        <td><%= scanner.match %></td>
        <td><%= scanner.tag %></td>
        <td><%= scanner.pattern %></td>
        <td><%= scanner.final %></td>
        <td><%= scanner.matchS(@url) %></td>

        <td><%= link_to material_icon.scanner.css_class('md-18'), scann_scanner_path(scanner, url: @url)  %></td>
        <td><%= link_to material_icon.fiber_new.css_class('md-18'), copy_scanner_path(scanner, urlExtern: @url) %></td>
        <td><%= link_to material_icon.mode_edit.css_class('md-18'), edit_scanner_path(scanner) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scanner', new_scanner_path %>

app/views/scanners/new.html.erb
<h1>New Scanner</h1>

<%= render 'form', scanner: @scanner %>

<%= link_to 'Back', scanners_path %>

app/views/scanners/scan.html.erb
<h1>Scan HTML Page</h1>

<%= render 'formScan', scanner: @scanner %>
<% if @links %>
<% @links.each do |link| %>

   <%=link_to link, link%>
<% end %>
<% end %>
<%= link_to 'Back', scanners_path %>

app/views/scanners/scanResult.html.erb
<p id="notice"><%= notice %></p>


  <strong>Scanned Url: </strong>
  <%= @url %>
</p>

Common Start:  <%= @commonStart %>

<ul>
<% @possibleLocations.each do |location| %>
<li> <%= link_to "SELECT", msas_scanners_path(url: @url, location_id: location, bookmark_id: @bookmark_id) %> 
   <%=location.name+ " "+location.uri %>
<% end %>
</ul>


<% if @lll %>
   <%= @lll.show.html_safe %>
<% end %>


<% if @lll %>
<% @lll.to_a.each do |link| %>
<% if link[2] == "x"
     m = "-------"
   else
     m = "Match"
   end
 %>
      <div style="padding-left: <%=link[1]*3%>em ">
    <%=link_to link[1], match_scanners_path(url: link[0]) %>
    <%=link_to link[0], link[0]%>
   <%= link[2] %> 
   </div>
    

    
<% end %>
<% end %>

<p>
<p>
<p>

<% if @links %>
<% @links.each do |link| %>
<% if link[2] == "x"
     m = "-------"
   else
   	 m = "Match"
   end
 %>
      <div style="padding-left: <%=link[1]*3%>em ">
    <%=link_to link[1], match_scanners_path(url: link[0]) %>
    <%=link_to link[0], link[0]%>
   <%= link[2] %> 
   </div>
    

	  
<% end %>
<% end %>

<%= link_to 'Back', scanners_path %>

app/views/scanners/scanResultYT.html.erb
<p id="notice"><%= notice %></p>


  <strong>Scanned Url: </strong>
  <%= @url %>
</p>

Possilbe File-Locations 
<ul>
<% @possibleLocations.each do |location| %>
<li> <%= link_to "SELECT", msytdl_scanners_path(url: @url, location_id: location, bookmark_id: @bookmark_id) %> 
   <%=location.name+ " "+location.uri %>
<% end %>
</ul>


<% if @lll %>
   <%= @lll.show.html_safe %>
<% end %>


<% if @lll %>
<% @lll.to_a.each do |link| %>
<% if link[2] == "x"
     m = "-------"
   else
     m = "Match"
   end
 %>
      <div style="padding-left: <%=link[1]*3%>em ">
    <%=link_to link[1], match_scanners_path(url: link[0]) %>
    <%=link_to link[0], link[0]%>
   <%= link[2] %> 
   </div>
    

    
<% end %>
<% end %>

<p>
<p>
<p>

<% if @links %>
<% @links.each do |link| %>
<% if link[2] == "x"
     m = "-------"
   else
   	 m = "Match"
   end
 %>
      <div style="padding-left: <%=link[1]*3%>em ">
    <%=link_to link[1], match_scanners_path(url: link[0]) %>
    <%=link_to link[0], link[0]%>
   <%= link[2] %> 
   </div>
    

	  
<% end %>
<% end %>

<%= link_to 'Back', scanners_path %>

app/views/scanners/scann.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Scanned Url: </strong>
  <%= @url %>
</p>
<p>
  <strong>Name:</strong>
  <%= @scanner.name %>
</p>
<p>
  <strong>Match:</strong>
  <%= @scanner.match %>
</p>
<p>
  <strong>Tag:</strong>
  <%= @scanner.tag %>
</p>

<p>
  <strong>Attribute:</strong>
  <%= @scanner.attr %>
</p>
<p>
  <strong>Pattern:</strong>
  <%= @scanner.pattern %>
</p>

<% if @links %>
<% @links.each do |link| %>
<li>  <%=link_to link, link%>
	  <%=link_to "Match", match_scanners_path(url: link) %>
    <%= %>
	
</li>
<% end %>
<% end %>

<%= link_to 'Edit', edit_scanner_path(@scanner) %> |
<%= link_to 'Back', scanners_path %>

app/views/scanners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tag:</strong>
  <%= @scanner.tag %>
</p>

<p>
  <strong>Pattern:</strong>
  <%= @scanner.pattern %>
</p>

<%= link_to 'Edit', edit_scanner_path(@scanner) %> |
<%= link_to 'Back', scanners_path %>