config/routes.rb
PMC4::Application.routes.draw do

  resources :notices
  get 'config/show' => 'config#show', as: 'show_config'

  get 'scanners/scan' => 'scanners#scan', as: 'scan_scanners'
  get 'scanners/match' => 'scanners#match', as: 'match_scanners'
  post 'scanners/match' => 'scanners#match', as: 'match_scanners_post'

  get 'scanners/msas' => 'scanners#msas', as: 'msas_scanners'
  get 'scanners/msytdl' => 'scanners#msytdl', as: 'msytdl_scanners' # youtube dl


  resources :scanners do
    get 'copy', :on => :member
    get 'scann', :on => :member
    get 'extract', :on => :member
    get 'extractsave', :on => :member
  end

  resources :bookmarks do
    get 'getTitle', :on => :member
    get 'scan', :on => :member
    post 'search', :on => :collection
    get 'linkFolder', :on => :member
  end

  resources :mtypes


  resources :matches do
    get 'match', :on => :collection
    get 'extract', :on => :member
    get 'extractsave', :on => :member

  end

  resources :regurls do

    get 'check', :on => :member
    get 'match', :on => :collection

  end


  resources :agroups
  patch 'agroups' => 'agroups#indexedit', as: 'indexedit_agroups'

  get 'attris/find' => 'attris#find', as: 'find_attris'
  get 'attris/indi' => 'attris#indi', as: 'indi_attris'
  get 'attris/:id/find' => 'attris#find', as: 'find_attris2'

  get 'uris/show'  => "uris#show", as: 'uris_show'
  get 'uris/matchURL'  => "uris#matchURL", as: 'matchURL_uris'
  get 'uris/matchDir'  => "uris#matchDir", as: 'uris_matchDir'

  get 'uris/fetch'  => "uris#fetch", as: 'fetch_uris'
  get 'uris/save'  => "uris#save", as: 'save_uris'

  get 'uris/getLinks'  => "uris#getLinks", as: 'getLinks_uris'

  resources :attris do
    get 'autocomplete', :on => :collection
    get 'overview', :on => :collection
  end

  resources :mfiles do
    post 'add_attri_name', :on => :member
    post 'add_attri', :on => :member
    delete 'remove_attri', :on => :member
    post 'add_agroup', :on => :member
    delete 'remove_agroup', :on => :member
    get 'edit0', :on => :member
    get 'new_tag', :on => :member
    get 'update_tag', :on => :member
    get 'delete_tag', :on => :member
    get 'pic', :on => :member
    get 'path', :on => :member
    get 'youtubeLink', :on => :member
    get 'renderMfile', :on => :member
    get  'classify', :on => :collection
    get  'slideshow', :on => :collection
    post 'set_attris', :on => :collection
    get  'thumbs', :on => :collection
    get 'download', :on => :member
  end

  resources :folders do
    post 'copyFiles', :on => :member
    post 'generateTNs', :on => :member
    get 'changeStorage', :on => :member
    post 'checkForVideoFiles', :on => :member

  end




  patch 'folders' => 'folders#indexedit', as: 'indexedit_folders'

  resources :locations do
    get 'analyzeFiles', :on => :member
    get 'deleteFiles', :on => :member
    get 'copyToFiles', :on => :member
    get 'downloadToFiles', :on => :member
    get 'parse', :on => :member
    get 'getTitle', :on => :member
    post 'gswl', :on => :member
    get 'checkAvail', :on => :member
    get 'parseURL', :on => :member
    get 'scan', :on => :member
    get 'ls', :on => :member
  end

  resources :storages do
    get 'detectfolders', :on => :member
    get 'detectfiles', :on => :member
    get 'detectFaFs', :on => :member
    get 'make_thumbnails', :on => :member
    post 'touchMfiles', :on => :member
    post 'generateTNs', :on => :member
  end










end

app/models/folder.rb
require 'open-uri'

class Folder < ActiveRecord::Base
  belongs_to :storage
  has_many :mfiles,  :dependent => :destroy
  has_one :bookmark
  
  def pathLocation(location)
 #    p = location.uri + "/" +  mpath + "/" +  lfolder + "/"
 #   p.gsub("///", "/").gsub("//", "/").gsub("//", "/").gsub("http:/","http://")
    location.uri + mpath + lfolder
  end

  def rpath
    File.join(mpath, lfolder)
  end

  def originPath
        ppath = storage.originPath
        ppath ? File.join(ppath,mpath,lfolder) : "<not defined>"
  end

  def path(typ)
    
#    Folder.resetFOLDERPATH
    if FOLDERPATH[typ] == nil 
       Folder.setFolderPath(typ)
    end
    if FOLDERPATH[typ][id] == nil
       setFolderPath(typ)
    end

    FOLDERPATH[typ][id] 
  end
   
  def setFolderPath(typ)
        
        return unless storage
        
        ppath = storage.path(typ)
        location = storage.location(typ)
        return unless location  #  important if a location for a certain type has not been defined
 #       a =  ppath+ "/" +  mpath + "/" +  lfolder + "/"

#        FOLDERPATH[typ][id]=  a.gsub("///", "/").gsub("//", "/").gsub("//", "/").gsub("http:/","http://")
        FOLDERPATH[typ][id]=   File.join(ppath,mpath,lfolder) # .gsub("http:/","http://")
#  
  end

  def Folder.setFolderPath(typ)
    
      FOLDERPATH[typ] = nil
      FOLDERPATH[typ] = Hash.new 
      fp = Folder.all
      fp.each do |f|
        storage = f.storage
        
        next unless storage
        
        ppath = storage.path(typ)
        location = storage.location(typ)
       
        next unless location  #  important if a location for a certain type has not been defined
       
        if typ == URL_STORAGE_WEBTN or typ == URL_STORAGE_FSTN
          tnprefix = location.prefix
          if (tnprefix && !tnprefix.empty?) or true # CHANGE 25.02.2015
              a =  ppath+   f.mpath +   f.lfolder + tnprefix
          else
             a =  ppath+ "/"  # relevant for thumbnails path in the old fashion
          end
        else 
          a =  ppath +  f.mpath +  f.lfolder 
          
        end 
        FOLDERPATH[typ][f.id]=  a
        
#        FOLDERPATH[typ][f.id]=  a.gsub("//", "/").gsub("//", "/").gsub("http:/","http://")
      end
  end
  
  def Folder.resetFOLDERPATH()
    FOLDERPATH.map! {|x| nil}  # puh, jetzt gehts
  end

  def resetFOLDERPATH()
    FOLDERPATH.map! {|x| 
      if x  
        x[id] = nil
      end
      x
      } 
  end
 
  def mkdir_DISABLED(toLocation)

     toStorage = toLocation.storage
     if toStorage != storage
      return
     end 
     uri = toLocation.uri
   
# check types   
     return "wrong typ in toLocation"   unless toLocation.typ == URL_STORAGE_FS  or toLocation.typ == URL_STORAGE_FSTN
   
     f = uri + "/"+ mpath + "/" + lfolder
     
     fsplit = f.split(/\//)
     fr = ""
     fsplit.each do |fs|
       next if fs == ""
       fr = File.join(fr,fs)
       puts "'"+f+"'"
       puts "dir='"+fr+"'"
       unless File.exist?(fr) 
          Dir.mkdir(fr)
       end
     end
  end


 def copyFiles(fromLocation, toLocation, force = false) # force implementierung fehlt noch für File Copy
   
   toStorage = toLocation.storage
   return "different storages" unless fromLocation.storage == toStorage
   
   return "folder is in different storage" unless toStorage.id == storage.id

   toUri = toLocation.uri
   fromUri = fromLocation.uri
# check types
#  return "wrong typ in fromLocation"  unless fromLocation.typ == URL_STORAGE_FS  or fromLocation.typ == URL_STORAGE_FSTN
   return "wrong typ in toLocation"    unless toLocation.typ == URL_STORAGE_FS  or toLocation.typ == URL_STORAGE_FSTN
   # todo: check FS or FSTN in common?
   

# get all folder from storage - fromLocation

   n = 0
  
   from = File.join(fromUri, mpath, lfolder).gsub("//", "/").gsub(":/","://")
   to =   File.join(toUri, mpath, lfolder)
     
#   mfiles = folder.mfiles
     
   mfiles.each do |mfile|           
        fromFile = File.join(from,mfile.filename)
        toFile   = File.join(to,mfile.filename)
        
        next if File.exist?(toFile) and not force # 20160108 

        x = toFile.split(/\//)
        checkpath  = "/"
        x = x[0,x.length-1]
        x.each {|p| checkpath = checkpath + "/" + p 
           unless File.exist?(checkpath)
             Dir.mkdir(checkpath)
           end          
        }

        if fromLocation.typ == URL_STORAGE_WEB           
              uri = URI.parse(URI.encode(fromFile))
              req = Net::HTTP::Get.new(uri.request_uri)
              req['Referer'] = uri.scheme+"://"+uri.host
              Net::HTTP.start(uri.host, uri.port) do |http|
                  response = http.request(req)
                 open(toFile, "wb") do |file|
                     file.write(response.body)
                     n = n +1
                 end
              end
        end
        
        if fromLocation.typ == URL_STORAGE_FS
          if File.exist?(fromFile) 
             FileUtils.cp(fromFile, toFile)
             n = n +1
          end
        end     
      break if n >20
   end
   return n.to_s+ " files copied"
 end


def generateTNs(fromLocation, toLocation, force=true, prefix, area)
   
   toStorage = toLocation.storage
   return "different storages" unless fromLocation.storage == toStorage
   toUri = toLocation.uri
   fromUri = fromLocation.uri
# check types
   return "wrong typ in fromLocation"  unless fromLocation.typ == URL_STORAGE_FS  
   return "wrong typ in toLocation"    unless toLocation.typ == URL_STORAGE_FSTN
   
   n = 0
   
   from = File.join(fromUri, mpath, lfolder)
   to =   File.join(toUri, mpath, lfolder)
     
     
   mfiles.each do |mfile|
        tofile = File.join(to,prefix+mfile.filename)
        next unless force or !File.exist?(tofile)  # 
        toLocation.createDirsIfNecessary(tofile) # 20171015
        
        fromfile = File.join(from,mfile.filename)
       
        case 
        when mfile.pic?
           tofile = tofile.gsub(".JPG",".jpg")
           if area == 0 
              command = "jhead -st \"" + tofile + "\"  \"" + fromfile  +"\""
           else
              command = "convert \""+ fromfile + "\" -thumbnail "+area.to_s+"@ \""+ tofile+"\""
           end
        when mfile.pdf?
              tofile = tofile.gsub(".pdf",".jpg").gsub(".PDF",".jpg")
              are = (area==0)?20000:area
              command = "convert \""+File.join(from,mfile.filename)+ "\"[0] -thumbnail "+are.to_s+"@ \""+ tofile+"\""
        else 
             command = nil
        end
        
        if command
           puts command
           system(command)
        end
        n = n + 1
   end
   return n.to_s+" thumbnails generated"
 end

def next
    f = Folder.where(storage_id: storage_id).where('id >?', id).order(id: :asc).first
    if f
      return f
    else
      return  Folder.where(storage_id: storage_id).first
    end
end

def previous
    f = Folder.where(storage_id: storage_id).where('id <?', id).order(id: :desc).take
    if f
      return f
    else
      return  Folder.where(storage_id: storage_id).last
    end
  end
  
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: [:show, :edit, :update, :destroy, :copyFiles, :generateTNs, :changeStorage, :checkForVideoFiles]

  # GET /folders
  # GET /folders.json
  def index
    @folders = Folder.all.order(:id)
        @numbers = Folder.joins(:mfiles).group('folders.id').count('mfiles.id')
        @numbersa = Folder.joins(mfiles: :agroups).group('folders.id').group('agroups.id').count('mfiles.id')
  #      @numbersa = Folder.joins(mfiles: :agroups).group('folders.id').count('mfiles.id')
    @agroups = Agroup.all

  end

  def indexedit
    @folders = Folder.all
  end

  # GET /folders/1
  # GET /folders/1.json
  def show
    
    session[:selectedFolder] = @folder.id
    session[:selectedFolderTitle] = @folder.title
    typ = params[:typ]
    if typ
      if typ == "next"
        @folder = Folder.find(@folder.id).next
        redirect_to folder_path(@folder)
      end
      if typ == "prev"
        @folder = Folder.find(@folder.id).previous
        redirect_to folder_path(@folder)
      end
      session[:selectedFolder] = @folder.id
    end
#    @mfiles = @folder.mfiles.reverse
    @mfiles = @folder.mfiles
#    @bookmark = Bookmark.find_by_folder_id(@folder.id)
    @bookmark =  @folder.bookmark
    @n = @folder.mfiles.count
  end

  # GET /folders/new
  def new
    @folder = Folder.new
  end

  # GET /folders/1/edit
  def edit
  end

  # POST /folders
  # POST /folders.json
  def create
    @folder = Folder.new(folder_params)

    respond_to do |format|
      if @folder.save
        format.html { redirect_to @folder, notice: 'Folder was successfully created.' }
        format.json { render action: 'show', status: :created, location: @folder }
      else
        format.html { render action: 'new' }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /folders/1
  # PATCH/PUT /folders/1.json
  def update
    respond_to do |format|
      if @folder.update(folder_params)
        @folder.resetFOLDERPATH # 07042018
        format.html { redirect_to @folder, notice: 'Folder was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /folders/1
  # DELETE /folders/1.json
  def destroy
    if bm = @folder.bookmark
       bm.folder_id = nil
       bm.save
    end
    @folder.destroy
    respond_to do |format|
      format.html { redirect_to folders_url }
      format.json { head :no_content }
    end
  end

# change storage
  def changeStorage
     @storage = Storage.find(params[:storage_id])
     op = @storage.originPath
     fp = @folder.originPath
     old_storage_id = @folder.storage.id

     if fp[op]
       @folder.mpath = fp.sub(op, "")
       @folder.storage_id = @storage.id
       @folder.save
       @folder.resetFOLDERPATH
     end
    redirect_to storage_path(old_storage_id, move: "x")
  end


# copy files from from origin location to location of type typ

  def copyFiles

    typString = params[:typ]
    dlm = params[:dlm]
    Config::Settings.dlm= dlm if dlm
    if typString
       typ = typString.to_i
       if typ == 1 or typ == 2 or typ == 3 or typ == 4
          toLocation = @folder.storage.location(typ)
          mk = toLocation.mkDirectories(@folder)
          if typ == 3 or typ == 4   # if thumbnails!
            message = @folder.storage.location(1).copyFiles(toLocation,@folder,true)
          else # if web 
            message = @folder.storage.originLocation.copyFiles(toLocation,@folder,false, 1000)
          end

          flash[:notice] = message
        end
    end
    redirect_to @folder
  end

  def generateTNs

    @folder.storage.location(4).mkDirectories
    message = @folder.generateTNs(@folder.storage.location(2), @folder.storage.location(4), true, "", 20000)

    flash[:notice] = message
    redirect_to @folder

  end
 
 def checkForVideoFiles

    location = @folder.storage.location(2) # filesystem
#    message = location.checkForVideoFiles

    mfiles = @folder.mfiles
    n = 0

    mfiles.each do |mfile|
       fp =  mfile.path(2)
       ext = ".mp4"
       fvideo = fp.gsub(/\.[\w]*$/, ext) 
#File.basename(fp) > xyz.mp4
#File.extname(fp) > .mp4
#File.basename(fp, ".mp4") > xyz
#File.basename(fp, ".*") > xyz
#File.dirname(fp) >  /synivideo/youtube"

       if fvideo != fp and File.exist?(fvideo)
          mfile.filename =  File.basename(fvideo)
          n = n + 1
          mfile.save
       end

    end
    if n > 0
      message = " >  " + n.to_s + " jpg files were switched to video Files"
    end
    flash[:notice] = message
    redirect_to @folder

end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_folder
      @folder = Folder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def folder_params
      params.require(:folder).permit(:storage_id, :title, :mpath, :lfolder, :mfile_id, :storage_id, :dlm)
    end
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/_form.html.erb
<%= form_for(@folder) do |f| %>
  <% if @folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
      <% @folder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class= "fieldbox">
  <div class="field">
    <%= f.label :storage_id %>
    <%= f.number_field :storage_id,  size: 100 %>
  </div>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title,  size: 90 %>
  </div>
  <div class="field">
    <%= f.label :mpath %>
    <%= f.text_field :mpath,  size: 90 %>
  </div>
  <div class="field">
    <%= f.label :lfolder %>
    <%= f.text_field :lfolder,  size: 90 %>
  </div>
  <div class="field">
    <%= f.label :mfile_id %>
    <%= f.number_field :mfile_id,  size: 100 %>
  </div>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/folders/edit.html.erb
<h1>Folder</h1>

<%= render 'form' %>

<%= link_to 'Show', @folder %> |
<%= link_to 'Back', folders_path %>

app/views/folders/index.html.erb
<h1>Folders</h1>

<table>
  <thead>
    <tr>
      <th>Storage </th>
      <th>Title</th>
      <th>Mpath</th>
      <th>Anzahl </th>

      <% @agroups.each do |agroup|%>
      <th><%=agroup.name%></th>
      <%end%>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @folders.each do |folder| %>
      <tr>
        <td><%= folder.storage.name%> </td>
       <td><%= folder.title %></td>
        <td><%= folder.mpath + " " + folder.lfolder%></td>
        <td><%= @numbers[folder.id] %></td>
        <% @agroups.each do |agroup|%>
        <% a = [folder.id,agroup.id] %>
        <th><%=(@numbersa[a]?@numbersa[a]*100/@numbers[folder.id]:0)%></th>
        <%end%>
        <td><%= link_to material_icon.search.css_class('md-18'), folder %></td>
        <td><%= link_to material_icon.delete.css_class('md-18'), folder , method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tbody>
</table>

<br>




<%= link_to 'Index to Edit', indexedit_folders_path, method: :patch %>

app/views/folders/indexedit.html.erb
<h1>Listing folders</h1>

<table>
  <thead>
    <tr>
      <th>Storage</th>
      <th>Mpath</th>
            <th>Path</th> 
      <th>Lfolder</th>
      <th>Mfile</th>
     <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @folders.each do |folder| %>
      <tr>
        <td><%= folder.storage_id %></td>
        <td><%= folder.mpath %></td>
                <td><%= folder.path(1) %></td>
        <td><%= folder.lfolder %></td>
        <td><%= folder.mfile_id %></td>
        <td><%= link_to 'Show', folder %></td>
        <td><%= link_to 'Edit', edit_folder_path(folder) %></td>
        <td><%= link_to 'Destroy', folder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Folder', new_folder_path %>

app/views/folders/new.html.erb
<h1>New folder</h1>

<%= render 'form' %>

<%= link_to 'Back', folders_path %>

app/views/folders/show.html.erb
<p id="notice"><%= notice %></p>


<div class="mdl-grid">

<div class="mdl-cell mdl-cell--1-col">
<h2>
Folder

</h2>
</div>


<div class="mdl-cell mdl-cell--9-col">

<h1>  <i class="titleName">   <%= @folder.title %>
  </i > 
</h1>



<div class= "valuepair">
 <div class="lbl">
  <strong>Path:</strong>
  </div>
<span> <%= @folder.mpath %> <%= @folder.lfolder %> </span>
</div>


<div class= "valuepair">
 <div class="lbl">
    Storage
  </div>
  <%= link_to @folder.storage.name, edit_storage_path(@folder.storage) %>
</div>


<div class= "valuepair">
 <div class="lbl">
  <strong>Orgin Bookmark:</strong>
  </div>
  <%=  (bm=@folder.bookmark) ? bm.url : "No Bookmark" %>
</div>
<p> 
<div class= "valuepair">
 <div class="lbl">
    Web Path:
  </div>
    <%=  @folder.path(1) %>
<%= form_tag(copyFiles_folder_path(@folder) )  do %>
<% end %>
</div>

<div class= "valuepair">
 <div class="lbl">
  <strong>Filesystem:</strong>
  </div>
  <%= link_to  @folder.path(2), ls_location_path(@folder.storage.location(2), dir: @folder.rpath) %>
</div>

<div class= "valuepair">
 <div class="lbl">
<strong>Web TNs Path:</strong>
  </div>
  <%= @folder.path(3) %>
</div>

<div class= "valuepair">
 <div class="lbl">
<strong>FS TNs Path:</strong>
  </div>
  <%= @folder.path(4) %>
</div>

<div class= "valuepair">
 <div class="lbl">
  <strong>Orgin Path:</strong>
  </div>
  <%= @folder.originPath %>
</div>

<div style="overflow:auto;height:200px">
<%= @n %>
<%= render 'shared/mfiles' %>

</div>

</div>

<div class="mdl-cell mdl-cell--2-col">
<h1>

    <%= link_to material_icon.list, folders_path %>
    <%= link_to material_icon.edit, edit_folder_path %>
    <% if @bookmark %>
       <%= link_to material_icon.bookmark, (bookmark_path(@bookmark)) %>
    <% end %>
    <%= link_to material_icon.chevron_left, folder_path(@folder, typ: :prev) %>
    <%= link_to material_icon.chevron_right, folder_path(@folder, typ: :next) %>

</h1>

<%= form_tag(copyFiles_folder_path(@folder) )  do %>

  <div class="actions">
    <%= hidden_field_tag :folder_id, {value: @folder.id} %>
    <%= hidden_field_tag :typ, 2 %>
    <%= hidden_field_tag :dlm, 2 %>
    
    <%= submit_tag "DL files from Origin to active File-System"%>
</div>
<% end %>

<%= form_tag(copyFiles_folder_path(@folder) )  do %>

  <div class="actions">
    <%= hidden_field_tag :folder_id, {value: @folder.id} %>
    <%= hidden_field_tag :typ, 2 %>
    <%= hidden_field_tag :dlm, 0 %>
    
    <%= submit_tag "direct-DL files from Origin to active File-System"%>
</div>
<% end %>



<%= form_tag(copyFiles_folder_path(@folder) )  do %>

  <div class="actions">
    <%= hidden_field_tag :folder_id, {value: @folder.id} %>
    <%= hidden_field_tag :typ, 4 %>
    
    <%= submit_tag "Make Thumbnails from active Webserver to active TN-Fileserver"%>
</div>
<% end %>


<%= form_tag(generateTNs_folder_path(@folder) )  do %>

  <div class="actions">
    <%= hidden_field_tag :folder_id, {value: @folder.id} %>
    
    <%= submit_tag "Generate Thumbnails"%>
</div>
<% end %>

<%= form_tag(copyFiles_folder_path(@folder) )  do %>

  <div class="actions">
    <%= hidden_field_tag :folder_id, {value: @folder.id} %>
    <%= hidden_field_tag :typ, 1 %>
    
    <%= submit_tag "Download files from Origin to active Web-Server"%>
</div>
<% end %>

<%= form_tag(copyFiles_folder_path(@folder) )  do %>

  <div class="actions">
    <%= hidden_field_tag :folder_id, {value: @folder.id} %>
    <%= hidden_field_tag :typ, 3 %>
    
    <%= submit_tag "Make Thumbnails from active Webserver to active TN-Webserver"%>
</div>
<% end %>

<%= form_tag(checkForVideoFiles_folder_path(@folder) )  do %>

  <div class="actions">
    <%= hidden_field_tag :folder_id, {value: @folder.id} %>
    <%= hidden_field_tag :typ, 2 %>
    
    <%= submit_tag "check for Video Files"%>
</div>
<% end %>


</div>
</div>
