config/routes.rb
PMC4::Application.routes.draw do

  resources :notices
  get 'config/show' => 'config#show', as: 'show_config'

  get 'scanners/scan' => 'scanners#scan', as: 'scan_scanners'
  get 'scanners/match' => 'scanners#match', as: 'match_scanners'
  post 'scanners/match' => 'scanners#match', as: 'match_scanners_post'

  get 'scanners/msas' => 'scanners#msas', as: 'msas_scanners'
  get 'scanners/msytdl' => 'scanners#msytdl', as: 'msytdl_scanners' # youtube dl


  resources :scanners do
    get 'copy', :on => :member
    get 'scann', :on => :member
    get 'extract', :on => :member
    get 'extractsave', :on => :member
  end

  resources :bookmarks do
    get 'getTitle', :on => :member
    get 'scan', :on => :member
    post 'search', :on => :collection
    get 'linkFolder', :on => :member
  end

  resources :mtypes


  resources :matches do
    get 'match', :on => :collection
    get 'extract', :on => :member
    get 'extractsave', :on => :member

  end

  resources :regurls do

    get 'check', :on => :member
    get 'match', :on => :collection

  end


  resources :agroups
  patch 'agroups' => 'agroups#indexedit', as: 'indexedit_agroups'

  get 'attris/find' => 'attris#find', as: 'find_attris'
  get 'attris/indi' => 'attris#indi', as: 'indi_attris'
  get 'attris/:id/find' => 'attris#find', as: 'find_attris2'

  get 'uris/show'  => "uris#show", as: 'uris_show'
  get 'uris/matchURL'  => "uris#matchURL", as: 'matchURL_uris'
  get 'uris/matchDir'  => "uris#matchDir", as: 'uris_matchDir'

  get 'uris/fetch'  => "uris#fetch", as: 'fetch_uris'
  get 'uris/save'  => "uris#save", as: 'save_uris'

  get 'uris/getLinks'  => "uris#getLinks", as: 'getLinks_uris'

  resources :attris do
    get 'autocomplete', :on => :collection
    get 'overview', :on => :collection
  end

  resources :mfiles do
    post 'add_attri_name', :on => :member
    post 'add_attri', :on => :member
    delete 'remove_attri', :on => :member
    post 'add_agroup', :on => :member
    delete 'remove_agroup', :on => :member
    get 'edit0', :on => :member
    get 'new_tag', :on => :member
    get 'update_tag', :on => :member
    get 'delete_tag', :on => :member
    get 'pic', :on => :member
    get 'path', :on => :member
    get 'youtubeLink', :on => :member
    get 'renderMfile', :on => :member
    get  'classify', :on => :collection
    get  'slideshow', :on => :collection
    post 'set_attris', :on => :collection
    get  'thumbs', :on => :collection
    get 'download', :on => :member
  end

  resources :folders do
    post 'copyFiles', :on => :member
    post 'generateTNs', :on => :member
    get 'changeStorage', :on => :member
    post 'checkForVideoFiles', :on => :member

  end




  patch 'folders' => 'folders#indexedit', as: 'indexedit_folders'

  resources :locations do
    get 'analyzeFiles', :on => :member
    get 'deleteFiles', :on => :member
    get 'copyToFiles', :on => :member
    get 'downloadToFiles', :on => :member
    get 'parse', :on => :member
    get 'getTitle', :on => :member
    post 'gswl', :on => :member
    get 'checkAvail', :on => :member
    get 'parseURL', :on => :member
    get 'scan', :on => :member
    get 'ls', :on => :member
  end

  resources :storages do
    get 'detectfolders', :on => :member
    get 'detectfiles', :on => :member
    get 'detectFaFs', :on => :member
    get 'make_thumbnails', :on => :member
    post 'touchMfiles', :on => :member
    post 'generateTNs', :on => :member
  end










end

app/views/shared/_assign_attris.html.erb
<div class='attriAssign'>

<% @attris = @mfile.attris
 %>

	<%= form_tag add_attri_name_mfile_path(@mfile), remote: true do%>
	<%= text_field_tag :name, "", data: {autocomplete_source: autocomplete_attris_path}, autofocus: :autofocus%>

	<%= submit_tag "ADD"%>
	<% end%>



<% @agroupssel = @mfile.agroups
   @agroups = Agroup.all
   
   @agroups.each do |agroup| %>
   	
   	<div>
    <% if @agroupssel.include?(agroup)%>
    	
    	   <div class='agroup_yes'> <%= agroup.name %> 
              <%= link_to 'X', remove_agroup_mfile_path(@mfile)+"?agroup_id="+agroup.id.to_s, method: :delete, remote: true%>
          </div>
    <% else%>
    
           <div class='agroup_no'> <%= agroup.name %> 
              <%= link_to '+', add_agroup_mfile_path(@mfile)+"?agroup_id="+agroup.id.to_s, method: :post, remote: true%>
           </div>
   <% end %>
   
   
   <%  @attris.each do |attri| %>
      <% if attri.agroup_id == agroup.id%>
        <div class='attribute'> <%= attri.name %> 
          <%= link_to 'X', remove_attri_mfile_path(@mfile)+"?attri_id="+attri.id.to_s, confirm: 'Are you sure?', method: :delete, remote: true%>
         </div>
      <%end %>  
   <% end %>
 
   </div>
 
 <% end %>
 
 
 <div style="clear: both;"></div>
   

</div>

app/views/shared/_edit_tag.html.erb
<div class='editTag' draggable='true'>

<% @tag = @media_object.tag %>

<%if @tag%>

<%= form_for(@tag, remote: true) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%=link_to "Delete Notice", delete_tag_media_object_path(@media_object), remote: true %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, rows: 10 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%else%>
<%=link_to "New Notice", new_tag_media_object_path(@media_object), remote: true %>
<% end %>

</div>

app/views/shared/_folder_attris.html.erb
<div class='attriFolder'>

  
 
 <div style="clear: both;"></div>
    <%  @attrisFolder.each do |attri| %>
        <div class='attribute'> 
          <%= link_to attri[1], add_attri_mfile_path(@mfile)+"?attri_id="+attri[0].to_s,  method: :post, remote: true%>
         </div>
   <% end %>
   

</div>

app/views/shared/_folders.html.erb
<h1>Folders</h1>

<table>
  <thead>
    <tr>
      <th>Storage </th>
      <th>Title</th>
      <th>Mpath</th>

      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @folders.each do |folder| %>
      <tr>

        <td><%= folder.storage.name%> </td>
       <td><%= folder.title %></td>
        <td><%= folder.mpath + " " + folder.lfolder%></td>
        <td><%= @numbers[folder.id] %></td>

        <td><%= link_to material_icon.search.css_class('md-18'), folder %></td>
        <td><%= link_to material_icon.delete.css_class('md-18'), folder , method: :delete, data: { confirm: 'Are you sure?' } %></td>

    <% end %>
  </tbody>
</table>

<br>

app/views/shared/_foldersm.html.erb
<h2>Folders</h2>

<table>
  <thead>
    <tr>
      <th>Mpath</th>
      <th>Name</th>
           <th>Storage Id</th>
      <th>Change Storage to </th>
    </tr>
  </thead>

  <tbody>
    <% @folders.each do |folder| %>
      <tr>

        <td><%= folder.mpath %></td>
        
        <td><%= folder.lfolder %></td>
                    <td><%= folder.storage_id%> </td>
 <td>   <%     f = folder.originPath %> 
           
         <%  @storages.each do |s| %>
        <% p = s.originPath          
        %>
         <%= f.include?(p) ? (link_to p, changeStorage_folder_path(folder.id, storage_id: s.id)) : ""%>
    <% end %>
 
        </td>
    <% end %>
  </tbody>
</table>

<br>

app/views/shared/_mfiles.html.erb

<table>
  <thead>
    <tr>
      <th>Folder/URL</th>
      <th>Name</th>
      <th>Modified</th>
      <th>Mod date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @mfiles.each do |mfile| %>
      <tr>
        <td><%= link_to mfile.furlder, mfile.folder %></td>
        <td><%= link_to mfile.name, mfile.path(1) %></td>        
        <td><%= mfile.modified %></td>
        <td><%= mfile.mod_date %></td>
        <td><%= link_to 'Show', mfile %></td>
        <td><%= link_to 'Edit', edit_mfile_path(mfile) %></td>
        <td><%= link_to 'Destroy', mfile, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

