config/routes.rb
PMC4::Application.routes.draw do

  resources :notices
  get 'config/show' => 'config#show', as: 'show_config'

  get 'scanners/scan' => 'scanners#scan', as: 'scan_scanners'
  get 'scanners/match' => 'scanners#match', as: 'match_scanners'
  post 'scanners/match' => 'scanners#match', as: 'match_scanners_post'

  get 'scanners/msas' => 'scanners#msas', as: 'msas_scanners'
  get 'scanners/msytdl' => 'scanners#msytdl', as: 'msytdl_scanners' # youtube dl


  resources :scanners do
    get 'copy', :on => :member
    get 'scann', :on => :member
    get 'extract', :on => :member
    get 'extractsave', :on => :member
  end

  resources :bookmarks do
    get 'getTitle', :on => :member
    get 'scan', :on => :member
    post 'search', :on => :collection
    get 'linkFolder', :on => :member
  end

  resources :mtypes


  resources :matches do
    get 'match', :on => :collection
    get 'extract', :on => :member
    get 'extractsave', :on => :member

  end

  resources :regurls do

    get 'check', :on => :member
    get 'match', :on => :collection

  end


  resources :agroups
  patch 'agroups' => 'agroups#indexedit', as: 'indexedit_agroups'

  get 'attris/find' => 'attris#find', as: 'find_attris'
  get 'attris/indi' => 'attris#indi', as: 'indi_attris'
  get 'attris/:id/find' => 'attris#find', as: 'find_attris2'

  get 'uris/show'  => "uris#show", as: 'uris_show'
  get 'uris/matchURL'  => "uris#matchURL", as: 'matchURL_uris'
  get 'uris/matchDir'  => "uris#matchDir", as: 'uris_matchDir'

  get 'uris/fetch'  => "uris#fetch", as: 'fetch_uris'
  get 'uris/save'  => "uris#save", as: 'save_uris'

  get 'uris/getLinks'  => "uris#getLinks", as: 'getLinks_uris'

  resources :attris do
    get 'autocomplete', :on => :collection
    get 'overview', :on => :collection
  end

  resources :mfiles do
    post 'add_attri_name', :on => :member
    post 'add_attri', :on => :member
    delete 'remove_attri', :on => :member
    post 'add_agroup', :on => :member
    delete 'remove_agroup', :on => :member
    get 'edit0', :on => :member
    get 'new_tag', :on => :member
    get 'update_tag', :on => :member
    get 'delete_tag', :on => :member
    get 'pic', :on => :member
    get 'path', :on => :member
    get 'youtubeLink', :on => :member
    get 'renderMfile', :on => :member
    get  'classify', :on => :collection
    get  'slideshow', :on => :collection
    post 'set_attris', :on => :collection
    get  'thumbs', :on => :collection
    get 'download', :on => :member
  end

  resources :folders do
    post 'copyFiles', :on => :member
    post 'generateTNs', :on => :member
    get 'changeStorage', :on => :member
    post 'checkForVideoFiles', :on => :member

  end




  patch 'folders' => 'folders#indexedit', as: 'indexedit_folders'

  resources :locations do
    get 'analyzeFiles', :on => :member
    get 'deleteFiles', :on => :member
    get 'copyToFiles', :on => :member
    get 'downloadToFiles', :on => :member
    get 'parse', :on => :member
    get 'getTitle', :on => :member
    post 'gswl', :on => :member
    get 'checkAvail', :on => :member
    get 'parseURL', :on => :member
    get 'scan', :on => :member
    get 'ls', :on => :member
  end

  resources :storages do
    get 'detectfolders', :on => :member
    get 'detectfiles', :on => :member
    get 'detectFaFs', :on => :member
    get 'make_thumbnails', :on => :member
    post 'touchMfiles', :on => :member
    post 'generateTNs', :on => :member
  end










end

app/models/storage.rb
class Storage < ActiveRecord::Base
  has_many :locations
  has_many :folders,  :dependent => :destroy # too risky

  def originLocation
   locations.where(storage_id: id).where(origin: true).first
  end

  def originPath
     originLocation ? originLocation.uri : nil
  end

  def webLocation
   locations.where(storage_id: id).where(inuse: true, typ: 1).first
  end
  
  def location(typ)
     locations.where(storage_id: id).where(inuse: true, typ: typ).first
  end
  
  def path(typ)
    if l = location(typ)
      l.uri      
    else
          ""
    end
  end
  
  def touchMfiles
    @mfiles = getMfiles
    
    @mfiles.each do |mfile|

            modtime = File.new(mfile.path(URL_STORAGE_FS)).mtime
            mfile.modified = modtime
            mfile.mod_date = modtime
            mfile.save
    end
  end
  
  def getMfiles
    Mfile.joins(:folder => :storage).where("storages.id = ?", id).distinct.to_a
  end
end

app/controllers/storages_controller.rb
class StoragesController < ApplicationController
  before_action :set_storage, only: [:show, :edit, :update, :destroy, :touchMfiles, :generateTNs]
  # GET /storages
  # GET /storages.json
  
# =>  FILEPATH=55
  def index
    @storages = Storage.all
  end

  # GET /storages/1
  # GET /storages/1.json
  def show
    @folders = @storage.folders
    if params[:move]
      @storages = Storage.all
      render :showm
    end
    @f = @folders.map {|f| f.mfiles}
#    @mfiles =  @storage.getMfiles # 29.04.2018 not needed any longer
    @numbers = Folder.joins(:mfiles).group('folders.id').count('mfiles.id')

    @mtypes = Mfile.group(:mtype).count(:id) # brauche wir dies????
  end

  # GET /storages/new
  def new
    @storage = Storage.new
  end

  # GET /storages/1/edit
  def edit
    
  end

  # POST /storages
  # POST /storages.json
  def create
    @storage = Storage.new(storage_params)

    respond_to do |format|
      if @storage.save
          if @storage.id
            normalWeb = params[:normalWeb].strip
            if normalWeb != ""
                location = Location.new(name: normalWeb, typ: 1, uri: normalWeb, origin: false, inuse: true, storage_id: @storage.id)
                location.save
            end
            origin = params[:origin].strip
            if origin != ""
                location = Location.new(name: origin, typ: 1, uri: origin, origin: true, inuse: false, storage_id: @storage.id)
                location.save
            end

          end
        format.html { redirect_to @storage, notice: 'Storage was successfully created.' }
        format.json { render action: 'show', status: :created, location: @storage }
      else
        format.html { render action: 'new' }
        format.json { render json: @storage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /storages/1
  # PATCH/PUT /storages/1.json
  def update
    @storage.webLocation
    @storage.location(1)

    typs = params[:typ]
#    byebug eex
    @locations = Location.where(storage_id: @storage.id)
    
    for location in @locations
      location.inuse = false
      if typs
        typs.each do |key, value|   
          if value.to_i == location.id
             location.inuse = true
          end
        end
      end
      location.save
    end
    if typs
      for typ in typs do
          Folder.setFolderPath(typ[0].to_i)
      end
    end
    
    # locs = params[:location]
    # @locations = Location.where(storage_id: @storage.id)
    # for location in @locations
    # location.inuse = false
    # if locs
    # for loc in locs do
    # if loc[0].to_i == location.id
    # location.inuse = true
    # end
    # end
    # end
    # location.save
    # end

    # for loc in locs
    # location = Location.find(loc[0])
    # location.inuse = true
    # location.save
    # end

    respond_to do |format|
      if @storage.update(storage_params)
        format.html { render action: 'edit', notice: 'Storage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @storage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /storages/1
  # DELETE /storages/1.json
  def destroy
    @storage.destroy
    respond_to do |format|
      format.html { redirect_to storages_url }
      format.json { head :no_content }
    end
  end

 def touchMfiles
   
   @mfiles = @storage.touchMfiles
   @mtypes = Mfile.group(:mtype).count(:id)
   render "mfiles/index"
 end
 # Detect Folders for a storage
  # 
  def detectfolders
 
    @storage_id = params[:id]
    save = params[:save]
    
    @storage = Storage.find(@storage_id)
    @basepath = @storage.path(URL_STORAGE_FS) # take the filepath
    
    a = []
    get_all_folders("", "", a)
    @folders = a    
    
  #  render text: @folders.map {|a| a.lfolder+"/"+a.mpath}
    if  save == "yes"
      if !@folders.nil?
          Folder.resetFOLDERPATH
 #        Folder.setFolderPath(55)
          success = true
      for folder in @folders
        success = success & folder.save
      end
      if success
        flash[:notice] = 'Folders successfully added.'
      else
        flash[:notice] = 'Error occured during adding Folders.'
      end
    else
      flash[:notice] = 'No files to be added.'      
    end
    end


  end
  
  # Detect files and folders with new uri_handler
  
  def detectFaFs
    @storage_id = params[:id]    
    @storage = Storage.find(@storage_id)
    @basepath = @storage.path(URL_STORAGE_FS) # take the filepath  
    
    files = UriHandler.getFiles(@basepath,"")
    @links = UriHandler.match(files)
    render "uris/match"
  end
  
  # Detect files in folders
  # 
  def detectfiles
    @storage_id = params[:id];
    filter = params[:filter]
    if filter == nil
      filter = /./
    end

    @storage = Storage.find(@storage_id)
    folders = Folder.where(storage_id: @storage_id)
    
    @mfiles = []    
    for folder in folders
      fp = folder.path(URL_STORAGE_FS) # filepath
      d = Dir.entries(fp)
      @mfiles_temp = []
      for file in d
        if file == '.' or file == '..'
          next
        end
        if file =~ filter
        else 
          next
        end
        
        if File.directory?(fp+"/"+file)
        else
          if Mfile.find_by_folder_id_and_filename( folder.id, file)
          else
            mfile = Mfile.new()
            mfile.folder_id = folder.id
            mfile.filename = file
            modtime = File.new(mfile.path(URL_STORAGE_FS)).mtime
            mfile.modified = modtime
            mfile.mod_date = modtime
            mfile.mtype = MFILE_PHOTO # should be replaced by dependency of storage type
            @mfiles_temp << mfile
            #            @mfiles << mfile
          end
        end
      end
      if @mfiles_temp != nil
        #       puts @mfiles_temp[0].path(1)
        @mfiles_temp.sort! {|x,y| x.filename <=> y.filename}
        @mfiles += @mfiles_temp     
      end 
    end
    if @mfiles.nil?
      flash[:notice] = 'No new files detected.'  
    end
    
    if params[:save] == "yes"
      
      if !@mfiles.nil?
      success = true
      for mfile in @mfiles
        success = success & mfile.save
      end
      if success
        flash[:notice] = 'Media Files successfully added.'
      else
        flash[:notice] = 'Error occured during adding Media Files.'
      end
    end
    end
    
  end
  
  def generateTNs
    
     fromLocation = @storage.location(URL_STORAGE_FS)
     toLocation   = @storage.location(URL_STORAGE_FSTN)


     @area = params[:area]    
     
     commit = params[:commit]    
     
     UriHandler.mkDirectories(toLocation)
     
     if commit == "Generate Thumbnails by Area"       
        text = UriHandler.generateTNs(fromLocation,toLocation,true,toLocation.prefix,@area)
    else
        text = UriHandler.generateTNs(fromLocation,toLocation,true,toLocation.prefix,0)      
     end

        
     flash[:notice] = text
     render "edit"
    
  end
  
  # generate the thumbnails for a given storage / OBSOLete
 
  def make_thumbnails
 
    @height = params[:height]
    @width = params[:width]
    @complete = params[:complete]
    @embedded = params[:embedded]
    @embedded = true
    @complete = true
       
    @storage_id = params[:id];
    @storage = Storage.find(@storage_id)
    
 #   fol = @storage.path(URL_STORAGE_FSTN)+"/"
    
    folders = @storage.folders
    
    if @embedded      # use embeded thumbnail pictures
      ja = "jhead -st "
    else             # generate thumbnails via java Thumbnail class
      ja = "java Thumbnail "
    end
    n = 0
    
    str = []
    
    for folder in folders
      
      mfiles = folder.mfiles
      for mfile in mfiles
        if @complete  || !File.exist?(mfile.path(URL_STORAGE_FSTN))

          if @embedded
             str[n] = ja + "\"" + mfile.path(URL_STORAGE_FSTN) + "\" "  +  "\""+ mfile.path(URL_STORAGE_FS) +"\"" 
 #            str[n] = ja + "\"" + fol + mfile.id.to_s + ".jpg\" " + "\""+ mfile.path(URL_STORAGE_FS) +"\"" 
               # leere Verzeichnsisstruktur erstellen geht mit:  xcopy e:\ c:\ /s/t 
             p str[n]
          else
            str[n] = ja + "\""+ mfile.path(URL_STORAGE_FS) +"\" \""+ fol + mfile.id.to_s + ".jpg\" "  +
            @width.to_s +  " " + @height.to_s + " 90"
          end
          puts str[n]
          n = n + 1
        end
      end
    end
    
 
 #   Thread.new do
      nn = 0
#      Thread.current[:no] = str.length
      session[:no_tns] = 0
      str.each do |st|
        nn = nn + 1
        system(st)        
#        Thread.current["nn"] = nn         
      end
#    end   
    redirect_to :action => 'index' 
    
  end
  
  
  private
  
  #------------------------------------------------
  
  
  def get_all_folders (mpath, lfolder, folders)
    if mpath == ""
      path = lfolder
    else
      path = mpath + "/" + lfolder
    end
    
    if path == ""
      complete_path = @basepath 
    else
      complete_path = @basepath + "/" + path
    end
    
    if complete_path == @storage.filepath_tn
      return
    end    
    
    d = Dir.entries(complete_path)
    # files
    for file in d
      if file == '.' or file == '..'
        next
      end
      if File.directory?(complete_path+"/"+file)
      else # it's a file and not a directory, therefore at least one file is in the directory
        
        if folder = Folder.find_by_storage_id_and_mpath_and_lfolder( @storage_id,
                                                           mpath,

app/helpers/storages_helper.rb
module StoragesHelper
end

app/views/storages/_form.html.erb
<%= form_for(@storage) do |f| %>
  <% if @storage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@storage.errors.count, "error") %> prohibited this storage from being saved:</h2>

      <ul>
      <% @storage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<% r = -1 %>
<%= submit_tag value="save", class: "buttonForm" %>

    
 <p>
<div class= "fieldbox">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name,  size: 80%>
  </div>

  <div class="field">
    <%= f.label :Type %>
    <%= f.select :mtype,
  MFILETYPE.map {|l| [l,r=r+1]},
  prompt: "Bitte wählen" %>
  </div>

<% if @storage.id  == nil %>
  <div class="field">
    <%= f.label :Origin %>
    <%= text_field_tag :origin,  nil, size: 80%>
  </div>
  <div class="field">
    <%= f.label  :NormalWeb%>
    <%= text_field_tag :normalWeb, nil,  size: 80%>
  </div>
<%end%>


<table>
  <tr>
   <th></th>
   <th> Name</th>
   <th>Uri</th>
       <th>Typ</th>
   <th><i class="fa fa-toggle-on lg"> </i>  </th>

  </tr>

<% @storage.locations.order(:typ).each do |location| %>
  <tr> 
        
        <td><%= link_to material_icon.fiber_new , new_location_path(:id => location.id)%></td>
        <td><%= link_to location.name, edit_location_path(location)%></td>
       <td><%= location.uri %></td>
       <td><%= TYPPP[location.typ] %></td>
       <td>  <%= radio_button_tag "typ["+location.typ.to_s+"]", location.id.to_s ,location.inuse %> </td>
       <td> <div  id="M1" class="processFiles" data-url='/locations/<%=location.id%>/analyzeFiles'> <%= material_icon.fingerprint   %></div> </td>
       <td> <div  class="processFiles" data-url='/locations/<%=location.id%>/deleteFiles'> <%= material_icon.delete if !location.inuse and location.isFS? %> </div> </td>
       <td> <div  class="processFiles" data-url='/locations/<%=location.id%>/copyToFiles' title="aa"> <%= material_icon.games  if location.copyAllowedTo?%></div> </td>
       <td> <div  id="M2" class="processFiles" data-url='/locations/<%=location.id%>/downloadToFiles'> <%= material_icon.redo  if location.downloadAllowedTo?%></div> </td>
       
  </tr>
<% end %>
</table>
<span class="mdl-tooltip" for="M1">Analyse</span>  
<span class="mdl-tooltip" for="M2"> Get Files	</span>  
  </div>
  <p>
  	
  <span class='clink'>
  <%= link_to "new location" , new_location_path(:storage_id => @storage.id) %>
  </span>
  
<% end %>

 <% if @storage.id%>
 

    <p>
    <%= form_tag generateTNs_storage_path(@storage), method: "post"  do %>
    
       <%= submit_tag value="Generate Thumbnails from internal Picture Thumbnails", class: "buttonForm" %>
       <p>
       
       <%= submit_tag value="Generate Thumbnails by Area", class: "buttonForm" %>
       <%= text_field_tag :area, value="20000"%>

    <% end %>
    
 <% end %>
    

      <span class='clink'>
<%= link_to 'Show', @storage %> |
<%= link_to 'List', storages_path %>
    </span>


app/views/storages/detectfiles.html.erb
<h1>Detected Media Files </h1>
<p id="notice"><%= notice %></p>

<table>
	 <th> ID </th>
  <th> full Path </th> <th> filename </th>
<% for mfile in @mfiles %>
   <tr>  <td> <%=mfile.id%></td>
   	     <td> <%=mfile.folder.path(55)%></td> <td> <%=mfile.filename%></td>  <th> Time </th>
   <td> <%=mfile.modified%></td> 
     <td> <%=mfile.mod_date%></td> 
   </tr>
<% end %>
</table>

<p>
<%= link_to 'Save New Mediafiles to Database', detectfiles_storage_path(@storage)+"?save=yes" %>
<%= link_to 'Storages List', storages_path %>



app/views/storages/detectfolders.html.erb
<h1>Detected Folders </h1>
<p id="notice"><%= notice %></p>
<table>
  <th>id</th> <th> Middle Path </th> <th> Folder </th>
<% for folder in @folders %>
   <tr>   <td> <%=folder.id%></td>  <td> <%=folder.mpath%></td> <td> <%=folder.lfolder%></td> </tr>
<% end %>
</table>

<p>
<%= link_to 'Save New Folders to Database', detectfolders_storage_path(@storage)+"?save=yes" %>
<%= link_to 'Storages List', storages_path %>


app/views/storages/edit.html.erb
<div class="mdl-grid">

<div class="mdl-cell mdl-cell--1-col">
<h1>
llll  lj l jl l l ll ll 

<%= link_to 'Show', @storage %> 
<%= link_to 'List', storages_path %>

</h1>
<p id="notice"><%= notice %></p>

</div>

<div class="mdl-cell mdl-cell--8-col">


<h1>Storage</h1>
<%= render 'form' %>



  <% if false%>
  <%= link_to 'Detect Files and Folders', detectFaFs_storage_path(@storage) %>
<p>
  <%= link_to 'Detect Folders', detectfolders_storage_path(@storage) %>
  <%= link_to 'Detect Files', detectfiles_storage_path(@storage) %>
   <%= link_to 'Make Thumbnails', make_thumbnails_storage_path(@storage) %>


  <%end%>
    <%= form_tag touchMfiles_storage_path(@storage), method: "post"  do %>

       <%= submit_tag("Set Dates of Mfiles in this Storage", class: "buttonForm") %>
    <% end %>
</div>
</div>

app/views/storages/index.html.erb
<div class="mdl-grid">

<div class="mdl-cell mdl-cell--1-col">
<h1>
<span><%= link_to material_icon.fiber_new, new_storage_path %> </span>
<span><%= link_to material_icon.fiber_new, new_storage_path %> </span>
<span><%= link_to material_icon.fiber_new, new_storage_path %> </span>
<span><%= link_to material_icon.fiber_new, new_storage_path %> </span>
</h1>
</div>


<div class="mdl-cell mdl-cell--10-col">

<h1>Storages

</h1>

<p>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @storages.each do |storage| %>
  <tr>
    <td><%= storage.name %></td>
    <td><%= link_to material_icon.search, storage %></td>
    <td><%= link_to material_icon.mode_edit, edit_storage_path(storage) %></td>
    <td><%= link_to material_icon.delete, storage, data: { confirm: 'Are you sure?'}, method: :delete %></td>
  </tr>
<% end %>
</table>

<br />


</div>

</div>

app/views/storages/new.html.erb
<h1>New storage</h1>

<%= render 'form' %>

<%= link_to 'Back', storages_path %>

app/views/storages/show.html.erb

<p id="notice"><%= notice %></p>

<h1> Storage   <i class="titleName"><%= @storage.name %> </i>

    <%= link_to material_icon.fiber_new, new_storage_path %>
    <%= link_to material_icon.list, storages_path %>
    <%= link_to  material_icon.mode_edit, edit_storage_path(@storage) %></td>
    <%= link_to  material_icon.delete, @folder, method: :delete, data: { confirm: 'Are you sure?' } %>

</h1>


<div class="fbox">
<%= render 'shared/folders' %>
</div>

<div class="fbox">
  render 'shared/mfiles'
</div>







app/views/storages/showm.html.erb
<p id="notice"><%= notice %></p>

<h1> Storage   <i class="titleName"><%= @storage.name %> </i>
</h1>


  <span class='clink'>
  	<%= link_to 'Edit', edit_storage_path(@storage) %> |
    <%= link_to 'Back', storages_path %>
  </span>

    <%= form_tag touchMfiles_storage_path(@storage), method: "post"  do %>

       <%= submit_tag("Set Dates of Mfiles in this Storage", class: "buttonForm") %>
    <% end %>

<div class="fbox">
<%= render 'shared/foldersm' %>
</div>